language: node_js

node_js:
  - 5

git:
  depth: 3

sudo: false

cache:
  directories:
    - node_modules

script:
  npm run $TEST_TYPE

env:
  matrix:
    - TEST_TYPE=build
    - TEST_TYPE=lint

branches:
  only:
    - master
